server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: {lava_password}
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 512
    youtubePlaylistLoadLimit: null
    playerUpdateInterval: 4
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: false
