CREATE ROLE synapse WITH PASSWORD '{pg_password}' LOGIN;
CREATE DATABASE synapse WITH OWNER synapse LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE synapse TO synapse;
